## DIP Switch 1
#set_location_assignment PIN_V11 -to <ENTITY_PORT_NAME_CONNECTED_TO_DIPSW1_1>
#set_location_assignment PIN_V10 -to <ENTITY_PORT_NAME_CONNECTED_TO_DIPSW1_2>
#set_location_assignment PIN_AB10 -to <ENTITY_PORT_NAME_CONNECTED_TO_DIPSW1_3>
#set_location_assignment PIN_AA10 -to <ENTITY_PORT_NAME_CONNECTED_TO_DIPSW1_4>
#set_location_assignment PIN_AB9 -to <ENTITY_PORT_NAME_CONNECTED_TO_DIPSW1_5>
#set_location_assignment PIN_AA9 -to <ENTITY_PORT_NAME_CONNECTED_TO_DIPSW1_6>
#set_location_assignment PIN_AB8 -to <ENTITY_PORT_NAME_CONNECTED_TO_DIPSW1_7>
#set_location_assignment PIN_AA8 -to <ENTITY_PORT_NAME_CONNECTED_TO_DIPSW1_8>
## DIP Switch 2
#set_location_assignment PIN_Y8 -to <ENTITY_PORT_NAME_CONNECTED_TO_DIPSW2_1>
#set_location_assignment PIN_AB7 -to <ENTITY_PORT_NAME_CONNECTED_TO_DIPSW2_2>
#set_location_assignment PIN_AA7 -to <ENTITY_PORT_NAME_CONNECTED_TO_DIPSW2_3>
#set_location_assignment PIN_Y7 -to <ENTITY_PORT_NAME_CONNECTED_TO_DIPSW2_4>
#set_location_assignment PIN_Y6 -to <ENTITY_PORT_NAME_CONNECTED_TO_DIPSW2_5>
#set_location_assignment PIN_AB5 -to <ENTITY_PORT_NAME_CONNECTED_TO_DIPSW2_6>
#set_location_assignment PIN_AA5 -to <ENTITY_PORT_NAME_CONNECTED_TO_DIPSW2_7>
#set_location_assignment PIN_AB4 -to <ENTITY_PORT_NAME_CONNECTED_TO_DIPSW2_8>
