#set_location_assignment PIN_N5 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_A[0]>
#set_location_assignment PIN_N6 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_A[1]>
#set_location_assignment PIN_P4 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_A[2]>
#set_location_assignment PIN_P5 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_A[3]>
#set_location_assignment PIN_W6 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_A[4]>
#set_location_assignment PIN_V7 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_A[5]>
#set_location_assignment PIN_V6 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_A[6]>
#set_location_assignment PIN_V5 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_A[7]>
#set_location_assignment PIN_V1 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_A[8]>
#set_location_assignment PIN_V4 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_A[9]>
#set_location_assignment PIN_U2 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_A[10]>
#set_location_assignment PIN_U8 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_A[11]>
#set_location_assignment PIN_V2 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_A[12]>
#set_location_assignment PIN_M6 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_BA[0]>
#set_location_assignment PIN_M7 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_BA[1]>
#set_location_assignment PIN_M1  -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_DQ[0]>
#set_location_assignment PIN_M2  -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_DQ[1]>
#set_location_assignment PIN_M3  -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_DQ[2]>
#set_location_assignment PIN_N1  -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_DQ[3]>
#set_location_assignment PIN_N2  -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_DQ[4]>
#set_location_assignment PIN_P1  -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_DQ[5]>
#set_location_assignment PIN_P2  -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_DQ[6]>
#set_location_assignment PIN_P3  -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_DQ[7]>
#set_location_assignment PIN_W1  -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_DQ[8]>
#set_location_assignment PIN_W2  -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_DQ[9]>
#set_location_assignment PIN_Y1  -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_DQ[10]>
#set_location_assignment PIN_Y2  -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_DQ[11]>
#set_location_assignment PIN_Y3  -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_DQ[12]>
#set_location_assignment PIN_AA1 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_DQ[13]>
#set_location_assignment PIN_AB3 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_DQ[14]>
#set_location_assignment PIN_AA4 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_DQ[15]>
#set_location_assignment PIN_R1 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_DQM[0]>
#set_location_assignment PIN_V3 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_DQM[1]>
#set_location_assignment PIN_U7  -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_CKE>
#set_location_assignment PIN_AA3 -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_CLK>
#set_location_assignment PIN_M5  -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_NCAS>
#set_location_assignment PIN_M4  -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_NRAS>
#set_location_assignment PIN_U1  -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_NCS>
#set_location_assignment PIN_R2  -to <ENTITY_PORT_NAME_CONNECTED_TO_SDRAM_NWE>
